Repository VesperAkshay/qr-code-generator, pull requests merged in 2024-10, with the labels that each got.

#23 Changed QR code scanner library
  .gitignore
  package-lock.json
  package.json
  src/components/QRScanner.js
  src/css/tailwind.css
Labels: enhancement, hacktoberfest, hactoberfest-accepted

#76 I have implemented the validation for the new users using firebase.
  src/App.js
  src/components/Login.js
  src/components/Navbar.js
  src/components/ProtectedRoute.js
  src/components/Register.js
  src/context/AuthContext.js
  src/firebase.js
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#82 Fixed the dropdown close issue on tap and the UI, implemented the dark mode feature on all the pages added some animations
  src/App.js
  src/components/BulkQRCode.js
  src/components/CategorySelector.js
  src/components/ColorPicker.js
  src/components/DownloadButton.js
  src/components/FileUploader.js
  src/components/ImageQRCodeGenerator.js
  src/components/Navbar.js
  src/components/PDFToQR.js
  src/components/Profile.js
  src/components/QRCodeCanvas.js
  src/components/QRCodeGenerator.js
  src/components/QRScanner.js
  src/components/Setting.js
  src/components/SizeSlider.js
  src/components/SocialMedia.js
  src/components/Support.js
  src/components/VCardForm.js
  src/components/WifiForm.js
  src/context/ThemeContext.js
  src/pages/DashboardPage.js
  src/pages/Home.js
  src/pages/ProfilePage.js
  src/pages/QRCodePage.js
  tailwind.config.js
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 3

#91 Implement Minimum Character Limit for Feedback Input
  .env
  package-lock.json
  package.json
  src/components/Support.js
  src/firebase.js
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2

#105 Fix login and signup page bugs
  src/components/Login.js
  src/components/Register.js
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#110 Created dedicated Contributing.md file & Updated README.md with Team Section and redirect.
  Contributing.md
  README.md
  src/assets/QR Code.png
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 1

#132 "Register with Google" button not working
  src/components/Register.js
  src/firebase.js
Labels: hacktoberfest, hacktoberfest-accepted, gssoc-ext, level 2
